name: Build Lens

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Export version to variable
        run: |
            export LENS_VERSION=$(cat version)
            echo "LENS_VERSION=$LENS_VERSION" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Update Lens
        run: |
          git clone https://github.com/lensapp/lens.git
          cp update.js lens/update.js
          cd lens
          git checkout v${{ env.LENS_VERSION }}
          node update.js
      - name: Build Lens
        run: |
          mkdir releasefiles
          make build
          cp dist/OpenLens-${{ env.LENS_VERSION }}-latest.*.x86_64.AppImage releasefiles/OpenLens-${{ env.LENS_VERSION }}.AppImage
          cp dist/OpenLens-${{ env.LENS_VERSION }}-latest.*.amd64.deb releasefiles/OpenLens-${{ env.LENS_VERSION }}.deb
          cp dist/OpenLens-${{ env.LENS_VERSION }}-latest.*.x86_64.rpm releasefiles/OpenLens-${{ env.LENS_VERSION }}.rpm
        shell: bash
        working-directory: lens
        env:
          APPBUNDLEID: "io.kontena.lens-app"
      - name: Calculate SHA256 checksum
        run: |
          for filename in OpenLens-${{ env.LENS_VERSION }}*; do shasum -a 256 ${filename} | tee ${filename}.sha256 ; done
        shell: bash
        working-directory: lens/releasefiles
      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: v${{ env.LENS_VERSION }}
          files: | 
              lens/releasefiles/OpenLens-${{ env.LENS_VERSION }}.AppImage
              lens/releasefiles/OpenLens-${{ env.LENS_VERSION }}.deb
              lens/releasefiles/OpenLens-${{ env.LENS_VERSION }}.rpm
              lens/releasefiles/OpenLens-${{ env.LENS_VERSION }}*.sha256
      - name: Latest
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: Latest
          files: | 
              lens/dist/OpenLens*.AppImage
              lens/dist/OpenLens*.deb
              lens/dist/OpenLens*.rpm
              lens/dist/lates*.yml
